### ISSUE TITLE
check db table creation for orderManagment

### ISSUE THREAD

**Issue by TKSpectro** [fh-erfurt/WatchMyWatch#10]

**Comment by GrafGraph** [comment]
Shoppingcart und Payment passt so. Die Tabelle Order selbst fehlt: Es gibt eine ACCOUNT_ORDER Tabelle, die ähnlich wie eine n:m Beziehungstabelle aussieht, aber nicht zu der eigentlichen Beziehung (1 Account : n Orders) passt.
Außerdem werden die Enums noch ohne Constraints als int in der DB gespeichert.
TODO: Beziehung Account:Order überarbeiten und Tabelle Order einrichten. Außerdem Enums in DB anpassen

**Comment by TKSpectro** [comment]
Du kannst die Enums einfach umsetzen lassen durch: "@Enumerated(EnumType.STRING)"
also z.B.:
Beispiel aus Bracelet.java
"
    @Enumerated(EnumType.STRING)
    private ConnectionType connection;
"

https://tomee.apache.org/examples-trunk/jpa-enumerated/
@Maffotter @kanton1998
